# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Deply gh-pages

on:
  workflow_dispatch:
jobs:
  settings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Enable Yarn
        run: corepack enable
      - name: Create template
        run: yarn create react-app . --template awesome-soho
      - uses: actions/upload-artifact@v3
        with:
          name: template-init
          path: ./*
          if-no-files-found: error
  build:
    needs: settings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: template-init
      - name: Confirm build files
        run: ls -al
      - name: Build app
        run: yarn build
      - name: Confirm build files
        run: ls -al ./build
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build
          if-no-files-found: error
  deploy:
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
      - name: Confirm build files
        run: ls -al ./build
      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
